##
# Backend
-
  name:  'Backend'
  uriPattern: 'neniri/<BackendSubRoutes>'
  defaults:
    '@package': 'Neniri.App'
    '@action': 'index'
    '@format': 'html'
  subRoutes:
    'BackendSubRoutes':
      package: 'Neniri.App'
      suffix: 'Backend'

##
# Frontend
-
  name:  'Frontend'
  uriPattern: 'system/<FrontendSubRoutes>'
  defaults:
    '@package': 'Neniri.App'
    '@action': 'index'
    '@format': 'html'
  subRoutes:
    'FrontendSubRoutes':
      package: 'Neniri.App'
      suffix:  'Frontend'

##
# Default
-
  name: 'Sign up'
  uriPattern: 'signup'
  defaults:
    '@package': 'Neniri.App'
    '@controller': 'Registration'
    '@action': 'index'
    '@format': 'html'
  httpMethods: [GET]

-
  name: 'Password forgotten'
  uriPattern: 'reset'
  defaults:
    '@package': 'Neniri.App'
    '@controller': 'PasswordForgotten'
    '@action': 'index'
    '@format': 'html'
  httpMethods: [GET]

-
  name: 'Login'
  uriPattern: 'login'
  defaults:
    '@package': 'Neniri.App'
    '@controller': 'Login'
    '@action': 'index'
    '@format': 'html'
  httpMethods: [GET]

-
  name: 'Logout'
  uriPattern: 'logout'
  defaults:
    '@controller': 'Login'
    '@action': 'logout'
    '@format': 'html'
  httpMethods: [POST]

-
  name: 'Authenticate'
  uriPattern: 'authenticate'
  defaults:
    '@package': 'Neniri.App'
    '@controller': 'Login'
    '@action': 'authenticate'
    '@format': 'html'
  httpMethods: [POST]
