Neniri:
  App:
    title: 'Neniri'
    subtitle: ''
    userRole: 'Neniri.App:Employee' # employee role
    frontendUserRole: 'Neniri.App:Customer' # customer cole

Neos:
  Flow:
    mvc:
      routes:
        'Neniri.App': true
    http:
      applicationToken: ApplicationName
    security:
      authentication:
        providers:
          'Neniri.App:Employee':
            label: 'Backend'
            provider: PersistedUsernamePasswordProvider
#            requestPatterns:
#              'Neniri.App.Backend:StandardController':
#                pattern: 'ControllerObjectName'
#                patternOptions:
#                  controllerObjectNamePattern: 'Neos\Neos\Controller\StandardController'
            entryPoint: WebRedirect
            entryPointOptions:
              routeValues:
                '@package': 'Neniri.App'
                '@controller': 'Backend\Login'
                '@action': 'index'
                '@format': 'html'
          'Neniri.App:Customer':
            provider: PersistedUsernamePasswordProvider