Neniri:
  App:
    # how long is the activation token valid?
    activationTokenTimeout: '30 days'
    # how long is the password token valid?
    resetPasswordTokenTimeout: '1 day'
Neos:
  Flow:
    mvc:
      routes:
        'Neniri.App': true
    http:
      applicationToken: ApplicationName
    security:
      authentication:
        providers:
          'Neniri.App:User':
            label: 'Backend'
            provider: PersistedUsernamePasswordProvider
#            requestPatterns:
#              'Neniri.App.Backend:StandardController':
#                pattern: 'ControllerObjectName'
#                patternOptions:
#                  controllerObjectNamePattern: 'Neos\Neos\Controller\StandardController'
            entryPoint: WebRedirect
            entryPointOptions:
              routeValues:
                '@package': 'Neniri.App'
                '@controller': 'Login'
                '@action': 'index'
                '@format': 'html'