Neniri:
  App:
    # Run Neniri in debug mode
    debugMode: false
    acpUserRole: 'Neniri.App:AcpUser'
    frontendUserRole: 'Neniri.App:FrontendUser'

Neos:
  Flow:
    mvc:
      routes:
        'Neniri.App': true
    http:
      applicationToken: ApplicationName
    security:
      authentication:
        providers:
          'Neniri.App:AcpUser':
            provider: 'PersistedUsernamePasswordProvider'
          'Neniri.App:FrontendUser':
            provider: 'PersistedUsernamePasswordProvider'